name 'netcommons'
maintainer 'Kohei Teraguchi'
maintainer_email 'kteraguchi@commonsnet.org'
license 'NetCommons License'
description 'Installs/Configures netcommons'
long_description 'Installs/Configures netcommons'
version '0.1.0'

depends 'system'
depends 'locale'
depends 'git'
depends 'apache2'
depends 'php'
depends 'composer'
depends 'mariadb'
depends 'nodejs'
depends 'yum-epel'
